### ISSUE TITLE
remove divider / separator possible ?

### ISSUE THREAD

**Issue by wackowizzard** [jesscXC/hide-finder-trash-dock-icons#1]
Is it possible to remove the default divider of the dock as well (in Sierra) ?

**Comment by jesscxc** [comment]
I'm running High Sierra (macOS 10.13), now, and haven't made time to update the script. I trust my past self, so if it was possible to remove that divider when I wrote the script (2013December), I probably would have done it.

If you can do some research and find out one way or the other, I'd appreciate you letting me know so I can add that to the README to save others some time.  :)
