### ISSUE TITLE
Is there any way to hide the saparator in dock

### ISSUE THREAD

**Issue by eret9616** [jesscXC/hide-finder-trash-dock-icons#2]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/12445095/74806916-2bf9b500-5322-11ea-805a-cdd40166c298.png">

Now I've successful remove finder icon and trash icon, but there is a separator in the right, I'm using Catalina

And i restart the computer,the separator is in the left ...
<img width="352" alt="image" src="https://user-images.githubusercontent.com/12445095/74807992-ca871580-5324-11ea-9038-de3ca31cbaa8.png">

I don't know which file to edit, how to do this?

**Comment by jesscxc** [comment]
Hi!

Unfortunately my main computer isn't macOS right now; IIRC there wasn't an easy way to hide that separator. :(
