### ISSUE TITLE
get run error 1719

### ISSUE THREAD

**Issue by howhuai** [jesscXC/hide-finder-trash-dock-icons#3]
i run the script and got the error
`number -1719 from checkbox 3 of window 1 of process "System Preferences"`
invalid index 3

**Comment by jesscxc** [comment]
Hi!

What version of macOS are you using?

**Comment by whispy** [comment]
I get the same error. I'm running macOS 11.2.3.

If I remove all references to `toggle_indicator_lights()` (to try bypassing this function), I then get a different error:
```
error "System Events got an error: Can’t get menu 1 of UI element \"Finder\" of list 1 of process \"Dock\". Invalid index." number -1719 from menu 1 of UI element "Finder" of list 1 of process "Dock"
```

**Comment by jesscxc** [comment]
Hello, please try the updated README instructions with updated version of the script/app.

I tested on macOS High Sierra (v10.13.6) and was successful in running the script directly, as well as creating the .app and running that at login. It's a fairly fresh install of macOS.

I can make another version without the "toggle indicator lights" feature, if that seems to be an issue with the setup you're using. If you want to disable that function yourself, I added instructions in the README and script.

The error message `error "System Events got an error: Can't get menu 1 of UI element \"Finder\" of list 1 of process \"Dock\". Invalid index." number -1719 from menu 1 of UI element "Finder" of list 1 of process "Dock"` kind of seems like the `DockMenus.plist` file wasn't changed, perhaps? I think the `Invalid index` aspect refers to a menu item not being there to change ("index" referring to the position in a list).

I hope this helps!!

**Comment by whispy** [comment]
@jesscXC I figured out the issue — the `DockMenus.plist` file cannot be edited or overwritten whole SIP is enabled. The user would need to disable SIP to change that file.

**Comment by jesscxc** [comment]
Thank you!!

Were you able to successfully get the app to work?

**Comment by whispy** [comment]
I have not tried it yet, as I haven't had the time to disable SIP (and I'm not sure the security impact is worth it). I have to investigate further. If I end up doing it and it's successful, I'll definitely let you know! :D

**Comment by jesscxc** [comment]
You can toggle it on and off right a reboot (that's what I do). :)
